#!/bin/bash
# Author: Nick Zwart
# Date: 2022jan25
# Brief: a script that can copy the vim and vimrc directories to HOME and
#        modify the background to either dark or light.
#        Also append an alias for ni -> vim.
#        Also add my gitconfig.
#        Also install Ale

######################################################################## STRICT
# strict mode settings
set -euo pipefail
IFS=$'\n\t'


########################################################################### CLI
BKGND_COLOR=${1:-dark}


########################################################################## MAIN
# copy the cursed vim config
cp -rv vim "$HOME/.vim"
cp -v gitconfig "$HOME/.gitconfig"

# modify based on first arg
sed "s/^set\ background.*/set\ background=${BKGND_COLOR}/g" < vimrc > "$HOME/.vimrc"

# install ale
mkdir -p "$HOME/.vim/pack/git-plugins/start"
git clone --depth 1 https://github.com/dense-analysis/ale.git "$HOME/.vim/pack/git-plugins/start/ale"

# make a ni executable link to vim
ln -s "$(command -v vim)" /usr/bin/ni
