#!/bin/bash
# Author: Nick Zwart
# Date: 2019dec31
# Brief: push the docker image to dockerhub


####################################################################### INCLUDE
# assume config is in the same dir
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/config.bash ; config


########################################################################## MAIN
docker push ${DOCKER_ACC}/${DOCKER_REP}:${DOCKER_TAG}
